openapi: 3.1.0
info:
  title: Sidekick Control API
  version: 0.0.3
servers:
- url: http://127.0.0.1:28765
paths:
  /v1/health:
    get:
      operationId: GetHealth
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
          description: Successful Response
      summary: Health
  /v1/guilds/{guild_id}/clips:
    get:
      operationId: ListClips
      parameters:
      - explode: false
        in: path
        name: guild_id
        required: true
        schema:
          exclusiveMinimum: true
          format: int64
          minimum: 0
          title: Guild Id
          type: integer
        style: simple
      - explode: true
        in: query
        name: search
        required: false
        schema:
          maxLength: 64
          minLength: 1
          nullable: true
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListClipsResponse"
          description: Successful Response
        "401":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
          description: Unauthorized error response.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
          description: Internal error response.
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
          description: Validation Error
      security:
      - APIKeyHeader: []
      summary: List Clips
  /v1/guilds/{guild_id}/clips/play:
    post:
      operationId: PlayClip
      parameters:
      - explode: false
        in: path
        name: guild_id
        required: true
        schema:
          exclusiveMinimum: true
          format: int64
          minimum: 0
          title: Guild Id
          type: integer
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PlayClipBody"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlayClipResponse"
          description: Successful Response
        "401":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
          description: Unauthorized error response.
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
          description: Bad request error response.
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
          description: Clip not found error response.
        "409":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
          description: Voice not connected error response.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
          description: Internal error response.
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
          description: Validation Error
      security:
      - APIKeyHeader: []
      summary: Play Clip
  /v1/guilds/{guild_id}/clips/play-random:
    post:
      operationId: PlayRandomClip
      parameters:
      - explode: false
        in: path
        name: guild_id
        required: true
        schema:
          exclusiveMinimum: true
          format: int64
          minimum: 0
          title: Guild Id
          type: integer
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PlayRandomClipBody"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlayRandomClipResponse"
          description: Successful Response
        "401":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
          description: Unauthorized error response.
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
          description: Clip not found error response.
        "409":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
          description: Voice not connected error response.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
          description: Internal error response.
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
          description: Validation Error
      security:
      - APIKeyHeader: []
      summary: Play Random Clip
  /v1/guilds/{guild_id}/clips/stop:
    post:
      operationId: StopClip
      parameters:
      - explode: false
        in: path
        name: guild_id
        required: true
        schema:
          exclusiveMinimum: true
          format: int64
          minimum: 0
          title: Guild Id
          type: integer
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StopClipBody"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StopClipResponse"
          description: Successful Response
        "401":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
          description: Unauthorized error response.
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
          description: Guild not found error response.
        "409":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
          description: Voice not connected error response.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
          description: Internal error response.
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
          description: Validation Error
      security:
      - APIKeyHeader: []
      summary: Stop Clip
  /v1/guilds/{guild_id}/clips/stats/top:
    get:
      operationId: GetTopClipStats
      parameters:
      - explode: false
        in: path
        name: guild_id
        required: true
        schema:
          exclusiveMinimum: true
          format: int64
          minimum: 0
          title: Guild Id
          type: integer
        style: simple
      - explode: true
        in: query
        name: requester_user_id
        required: false
        schema:
          exclusiveMinimum: true
          format: int64
          minimum: 0
          title: Requester User Id
          type: integer
          nullable: true
        style: form
      - explode: true
        in: query
        name: days
        required: false
        schema:
          default: "7"
          pattern: ^(1|7|30|all)$
          title: Days
          type: string
        style: form
      - explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 10
          maximum: 50
          minimum: 1
          title: Limit
          type: integer
        style: form
      - explode: true
        in: query
        name: include_random
        required: false
        schema:
          default: false
          title: Include Random
          type: boolean
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TopClipStatsResponse"
          description: Successful Response
        "401":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
          description: Unauthorized error response.
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
          description: Bad request error response.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
          description: Internal error response.
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
          description: Validation Error
      security:
      - APIKeyHeader: []
      summary: Top Clip Stats
  /v1/guilds/{guild_id}/clips/stats/recent:
    get:
      operationId: GetRecentClipStats
      parameters:
      - explode: false
        in: path
        name: guild_id
        required: true
        schema:
          exclusiveMinimum: true
          format: int64
          minimum: 0
          title: Guild Id
          type: integer
        style: simple
      - explode: true
        in: query
        name: requester_user_id
        required: false
        schema:
          exclusiveMinimum: true
          format: int64
          minimum: 0
          title: Requester User Id
          type: integer
          nullable: true
        style: form
      - explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 10
          maximum: 50
          minimum: 1
          title: Limit
          type: integer
        style: form
      - explode: true
        in: query
        name: include_random
        required: false
        schema:
          default: true
          title: Include Random
          type: boolean
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RecentClipStatsResponse"
          description: Successful Response
        "401":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
          description: Unauthorized error response.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
          description: Internal error response.
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
          description: Validation Error
      security:
      - APIKeyHeader: []
      summary: Recent Clip Stats
  /v1/guilds/{guild_id}/intros/current:
    get:
      operationId: GetCurrentIntro
      parameters:
      - explode: false
        in: path
        name: guild_id
        required: true
        schema:
          exclusiveMinimum: true
          format: int64
          minimum: 0
          title: Guild Id
          type: integer
        style: simple
      - explode: true
        in: query
        name: requester_user_id
        required: true
        schema:
          exclusiveMinimum: true
          format: int64
          minimum: 0
          title: Requester User Id
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetCurrentIntroResponse"
          description: Successful Response
        "401":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
          description: Unauthorized error response.
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
          description: Bad request error response.
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
          description: Not found error response.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
          description: Internal error response.
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
          description: Validation Error
      security:
      - APIKeyHeader: []
      summary: Get Current Intro
    put:
      operationId: SetCurrentIntro
      parameters:
      - explode: false
        in: path
        name: guild_id
        required: true
        schema:
          exclusiveMinimum: true
          format: int64
          minimum: 0
          title: Guild Id
          type: integer
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SetCurrentIntroBody"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SetCurrentIntroResponse"
          description: Successful Response
        "401":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
          description: Unauthorized error response.
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
          description: Bad request error response.
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
          description: Not found error response.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
          description: Internal error response.
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
          description: Validation Error
      security:
      - APIKeyHeader: []
      summary: Set Current Intro
  /v1/guilds/{guild_id}/tags:
    get:
      operationId: ListTags
      parameters:
      - explode: false
        in: path
        name: guild_id
        required: true
        schema:
          exclusiveMinimum: true
          format: int64
          minimum: 0
          title: Guild Id
          type: integer
        style: simple
      - explode: true
        in: query
        name: search
        required: false
        schema:
          maxLength: 64
          minLength: 1
          nullable: true
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListTagsResponse"
          description: Successful Response
        "401":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
          description: Unauthorized error response.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
          description: Internal error response.
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
          description: Validation Error
      security:
      - APIKeyHeader: []
      summary: List Tags
  /v1/guilds/{guild_id}/tags/{tag_name}/clips:
    get:
      operationId: ListTagClips
      parameters:
      - explode: false
        in: path
        name: tag_name
        required: true
        schema:
          maxLength: 255
          minLength: 1
          title: Tag Name
          type: string
        style: simple
      - explode: false
        in: path
        name: guild_id
        required: true
        schema:
          exclusiveMinimum: true
          format: int64
          minimum: 0
          title: Guild Id
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListTagClipsResponse"
          description: Successful Response
        "401":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
          description: Unauthorized error response.
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
          description: Not found error response.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
          description: Internal error response.
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
          description: Validation Error
      security:
      - APIKeyHeader: []
      summary: List Tag Clips
    post:
      operationId: AddTagClip
      parameters:
      - explode: false
        in: path
        name: guild_id
        required: true
        schema:
          exclusiveMinimum: true
          format: int64
          minimum: 0
          title: Guild Id
          type: integer
        style: simple
      - explode: false
        in: path
        name: tag_name
        required: true
        schema:
          maxLength: 255
          minLength: 1
          title: Tag Name
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddTagClipBody"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AddTagClipResponse"
          description: Successful Response
        "401":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
          description: Unauthorized error response.
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
          description: Not found error response.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
          description: Internal error response.
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
          description: Validation Error
      security:
      - APIKeyHeader: []
      summary: Add Tag Clip
  /v1/guilds/{guild_id}/tags/{tag_name}/clips/{clip_trigger}:
    delete:
      operationId: RemoveTagClip
      parameters:
      - explode: false
        in: path
        name: guild_id
        required: true
        schema:
          exclusiveMinimum: true
          format: int64
          minimum: 0
          title: Guild Id
          type: integer
        style: simple
      - explode: false
        in: path
        name: tag_name
        required: true
        schema:
          maxLength: 255
          minLength: 1
          title: Tag Name
          type: string
        style: simple
      - explode: false
        in: path
        name: clip_trigger
        required: true
        schema:
          maxLength: 64
          minLength: 1
          title: Clip Trigger
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RemoveTagClipResponse"
          description: Successful Response
        "401":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
          description: Unauthorized error response.
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
          description: Not found error response.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorResponse"
          description: Internal error response.
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
          description: Validation Error
      security:
      - APIKeyHeader: []
      summary: Remove Tag Clip
components:
  schemas:
    AddTagClipBody:
      example:
        clip_trigger: clip_trigger
      properties:
        clip_trigger:
          maxLength: 64
          minLength: 1
          title: Clip Trigger
          type: string
      required:
      - clip_trigger
      title: AddTagClipBody
    AddTagClipResponse:
      example:
        tag_name: tag_name
        guild_id: 0
        clip_trigger: clip_trigger
        ok: true
      properties:
        ok:
          title: Ok
          type: boolean
        guild_id:
          format: int64
          title: Guild Id
          type: integer
        tag_name:
          title: Tag Name
          type: string
        clip_trigger:
          title: Clip Trigger
          type: string
      required:
      - clip_trigger
      - guild_id
      - ok
      - tag_name
      title: AddTagClipResponse
    ApiErrorResponse:
      example:
        code: code
        ok: true
        message: message
      properties:
        ok:
          title: Ok
          type: boolean
        code:
          title: Code
          type: string
        message:
          title: Message
          type: string
      required:
      - code
      - message
      - ok
      title: ApiErrorResponse
    ClipSummary:
      example:
        trigger: trigger
      properties:
        trigger:
          title: Trigger
          type: string
      required:
      - trigger
      title: ClipSummary
    GetCurrentIntroResponse:
      example:
        guild_id: 0
        requester_user_id: 6
        trigger: trigger
        ok: true
      properties:
        ok:
          title: Ok
          type: boolean
        guild_id:
          format: int64
          title: Guild Id
          type: integer
        requester_user_id:
          format: int64
          title: Requester User Id
          type: integer
        trigger:
          nullable: true
          type: string
      required:
      - guild_id
      - ok
      - requester_user_id
      title: GetCurrentIntroResponse
    HTTPValidationError:
      example:
        detail:
        - msg: msg
          loc:
          - Location_inner
          - Location_inner
          input: ""
          ctx: "{}"
          type: type
        - msg: msg
          loc:
          - Location_inner
          - Location_inner
          input: ""
          ctx: "{}"
          type: type
      properties:
        detail:
          items:
            $ref: "#/components/schemas/ValidationError"
          title: Detail
          type: array
      title: HTTPValidationError
    HealthResponse:
      example:
        service: service
        ok: true
        version: version
      properties:
        ok:
          title: Ok
          type: boolean
        service:
          title: Service
          type: string
        version:
          title: Version
          type: string
      required:
      - ok
      - service
      - version
      title: HealthResponse
    ListClipsResponse:
      example:
        total: 6
        search: search
        clips:
        - trigger: trigger
        - trigger: trigger
        guild_id: 0
        ok: true
      properties:
        ok:
          title: Ok
          type: boolean
        guild_id:
          format: int64
          title: Guild Id
          type: integer
        clips:
          items:
            $ref: "#/components/schemas/ClipSummary"
          title: Clips
          type: array
        total:
          title: Total
          type: integer
        search:
          nullable: true
          type: string
      required:
      - clips
      - guild_id
      - ok
      - total
      title: ListClipsResponse
    ListTagClipsResponse:
      example:
        total: 6
        tag_name: tag_name
        clips:
        - trigger: trigger
        - trigger: trigger
        guild_id: 0
        ok: true
      properties:
        ok:
          title: Ok
          type: boolean
        guild_id:
          format: int64
          title: Guild Id
          type: integer
        tag_name:
          title: Tag Name
          type: string
        clips:
          items:
            $ref: "#/components/schemas/TagClipSummary"
          title: Clips
          type: array
        total:
          title: Total
          type: integer
      required:
      - clips
      - guild_id
      - ok
      - tag_name
      - total
      title: ListTagClipsResponse
    ListTagsResponse:
      example:
        total: 6
        search: search
        guild_id: 0
        ok: true
        tags:
        - name: name
        - name: name
      properties:
        ok:
          title: Ok
          type: boolean
        guild_id:
          format: int64
          title: Guild Id
          type: integer
        tags:
          items:
            $ref: "#/components/schemas/TagSummary"
          title: Tags
          type: array
        total:
          title: Total
          type: integer
        search:
          nullable: true
          type: string
      required:
      - guild_id
      - ok
      - tags
      - total
      title: ListTagsResponse
    PlayClipBody:
      example:
        requester_user_id: 0
        trigger: trigger
        request_id: request_id
      properties:
        trigger:
          maxLength: 64
          minLength: 1
          title: Trigger
          type: string
        request_id:
          nullable: true
          type: string
        requester_user_id:
          exclusiveMinimum: true
          format: int64
          minimum: 0.0
          title: Requester User Id
          type: integer
      required:
      - requester_user_id
      - trigger
      title: PlayClipBody
    PlayClipResponse:
      example:
        guild_id: 0
        resolved_trigger: resolved_trigger
        trigger: trigger
        ok: true
        request_id: request_id
        status: playing
      properties:
        ok:
          title: Ok
          type: boolean
        guild_id:
          format: int64
          title: Guild Id
          type: integer
        trigger:
          title: Trigger
          type: string
        resolved_trigger:
          title: Resolved Trigger
          type: string
        status:
          enum:
          - playing
          title: Status
          type: string
        request_id:
          nullable: true
          type: string
      required:
      - guild_id
      - ok
      - resolved_trigger
      - status
      - trigger
      title: PlayClipResponse
    PlayRandomClipBody:
      example:
        requester_user_id: 0
        request_id: request_id
      properties:
        request_id:
          nullable: true
          type: string
        requester_user_id:
          exclusiveMinimum: true
          format: int64
          minimum: 0.0
          title: Requester User Id
          type: integer
      required:
      - requester_user_id
      title: PlayRandomClipBody
    PlayRandomClipResponse:
      example:
        guild_id: 0
        resolved_trigger: resolved_trigger
        ok: true
        request_id: request_id
        status: playing
      properties:
        ok:
          title: Ok
          type: boolean
        guild_id:
          format: int64
          title: Guild Id
          type: integer
        resolved_trigger:
          title: Resolved Trigger
          type: string
        status:
          enum:
          - playing
          title: Status
          type: string
        request_id:
          nullable: true
          type: string
      required:
      - guild_id
      - ok
      - resolved_trigger
      - status
      title: PlayRandomClipResponse
    RecentClipStatsItem:
      example:
        mode: direct
        played_at_utc: played_at_utc
        clip_id: 5
        trigger: trigger
      properties:
        clip_id:
          title: Clip Id
          type: integer
        trigger:
          title: Trigger
          type: string
        mode:
          enum:
          - direct
          - random
          title: Mode
          type: string
        played_at_utc:
          title: Played At Utc
          type: string
      required:
      - clip_id
      - mode
      - played_at_utc
      - trigger
      title: RecentClipStatsItem
    RecentClipStatsResponse:
      example:
        include_random: true
        guild_id: 0
        limit: 1
        requester_user_id: 6
        ok: true
        rows:
        - mode: direct
          played_at_utc: played_at_utc
          clip_id: 5
          trigger: trigger
        - mode: direct
          played_at_utc: played_at_utc
          clip_id: 5
          trigger: trigger
      properties:
        ok:
          title: Ok
          type: boolean
        guild_id:
          format: int64
          title: Guild Id
          type: integer
        requester_user_id:
          format: int64
          title: Requester User Id
          type: integer
          nullable: true
        limit:
          title: Limit
          type: integer
        include_random:
          title: Include Random
          type: boolean
        rows:
          items:
            $ref: "#/components/schemas/RecentClipStatsItem"
          title: Rows
          type: array
      required:
      - guild_id
      - include_random
      - limit
      - ok
      - rows
      title: RecentClipStatsResponse
    RemoveTagClipResponse:
      example:
        tag_name: tag_name
        guild_id: 0
        clip_trigger: clip_trigger
        ok: true
      properties:
        ok:
          title: Ok
          type: boolean
        guild_id:
          format: int64
          title: Guild Id
          type: integer
        tag_name:
          title: Tag Name
          type: string
        clip_trigger:
          title: Clip Trigger
          type: string
      required:
      - clip_trigger
      - guild_id
      - ok
      - tag_name
      title: RemoveTagClipResponse
    SetCurrentIntroBody:
      example:
        requester_user_id: 0
        trigger: trigger
      properties:
        requester_user_id:
          exclusiveMinimum: true
          format: int64
          minimum: 0.0
          title: Requester User Id
          type: integer
        trigger:
          maxLength: 64
          minLength: 1
          title: Trigger
          type: string
      required:
      - requester_user_id
      - trigger
      title: SetCurrentIntroBody
    SetCurrentIntroResponse:
      example:
        guild_id: 0
        requester_user_id: 6
        trigger: trigger
        ok: true
      properties:
        ok:
          title: Ok
          type: boolean
        guild_id:
          format: int64
          title: Guild Id
          type: integer
        requester_user_id:
          format: int64
          title: Requester User Id
          type: integer
        trigger:
          title: Trigger
          type: string
      required:
      - guild_id
      - ok
      - requester_user_id
      - trigger
      title: SetCurrentIntroResponse
    StopClipBody:
      example:
        requester_user_id: 0
        request_id: request_id
      properties:
        request_id:
          nullable: true
          type: string
        requester_user_id:
          exclusiveMinimum: true
          format: int64
          minimum: 0.0
          title: Requester User Id
          type: integer
      required:
      - requester_user_id
      title: StopClipBody
    StopClipResponse:
      example:
        guild_id: 0
        ok: true
        request_id: request_id
        status: stopped
      properties:
        ok:
          title: Ok
          type: boolean
        guild_id:
          format: int64
          title: Guild Id
          type: integer
        status:
          enum:
          - stopped
          title: Status
          type: string
        request_id:
          nullable: true
          type: string
      required:
      - guild_id
      - ok
      - status
      title: StopClipResponse
    TagClipSummary:
      example:
        trigger: trigger
      properties:
        trigger:
          title: Trigger
          type: string
      required:
      - trigger
      title: TagClipSummary
    TagSummary:
      example:
        name: name
      properties:
        name:
          title: Name
          type: string
      required:
      - name
      title: TagSummary
    TopClipStatsItem:
      example:
        clip_id: 5
        trigger: trigger
        play_count: 5
        last_played_at_utc: last_played_at_utc
      properties:
        clip_id:
          title: Clip Id
          type: integer
        trigger:
          title: Trigger
          type: string
        play_count:
          title: Play Count
          type: integer
        last_played_at_utc:
          title: Last Played At Utc
          type: string
      required:
      - clip_id
      - last_played_at_utc
      - play_count
      - trigger
      title: TopClipStatsItem
    TopClipStatsResponse:
      example:
        include_random: true
        guild_id: 0
        limit: 1
        requester_user_id: 6
        days: "1"
        ok: true
        rows:
        - clip_id: 5
          trigger: trigger
          play_count: 5
          last_played_at_utc: last_played_at_utc
        - clip_id: 5
          trigger: trigger
          play_count: 5
          last_played_at_utc: last_played_at_utc
      properties:
        ok:
          title: Ok
          type: boolean
        guild_id:
          format: int64
          title: Guild Id
          type: integer
        requester_user_id:
          format: int64
          title: Requester User Id
          type: integer
          nullable: true
        days:
          enum:
          - "1"
          - "7"
          - "30"
          - all
          title: Days
          type: string
        limit:
          title: Limit
          type: integer
        include_random:
          title: Include Random
          type: boolean
        rows:
          items:
            $ref: "#/components/schemas/TopClipStatsItem"
          title: Rows
          type: array
      required:
      - days
      - guild_id
      - include_random
      - limit
      - ok
      - rows
      title: TopClipStatsResponse
    ValidationError:
      example:
        msg: msg
        loc:
        - Location_inner
        - Location_inner
        input: ""
        ctx: "{}"
        type: type
      properties:
        loc:
          items:
            $ref: "#/components/schemas/Location_inner"
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
        input:
          title: Input
        ctx:
          title: Context
          type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    Location_inner:
      anyOf:
      - type: string
      - type: integer
  securitySchemes:
    APIKeyHeader:
      in: header
      name: X-Sidekick-Token
      type: apiKey

